// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDofFDgj0khESt0SuFqXR2c-B0JRQdlFU',
    appId: '1:490198847296:android:6756a84bb86c42064bf4a5',
    messagingSenderId: '490198847296',
    projectId: 'ze-optic',
    databaseURL: 'https://ze-optic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ze-optic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHuFwwCS0aEFqTIIAuO_8Hqx39b46Ujc',
    appId: '1:490198847296:ios:916d521d9edf3c184bf4a5',
    messagingSenderId: '490198847296',
    projectId: 'ze-optic',
    databaseURL: 'https://ze-optic-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ze-optic.appspot.com',
    iosBundleId: 'com.example.zeOpticTech',
  );

}